# Generated by Django 4.0.2 on 2022-07-30 15:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_imagesforuser_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagesForUser',
            new_name='Profile',
        ),
    ]
