# Generated by Django 4.0.2 on 2022-07-20 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(upload_to='photos')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('status', models.CharField(choices=[('NR', 'Not read yet'), ('A', 'Answered'), ('E', 'Evalueted'), ('D', 'Discarded')], default='NR', max_length=2)),
                ('text', models.TextField(verbose_name='Your question')),
                ('answer', models.TextField(default=None, null=True)),
                ('isNotification', models.BooleanField(default=False)),
                ('isDone', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.lecturer')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ('-id',),
            },
        ),
    ]
