# Generated by Django 4.0.2 on 2022-07-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='creator',
            new_name='lecturer',
        ),
    ]
