# Generated by Django 4.0.2 on 2022-07-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_ticket_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='lecturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.lecturer'),
            preserve_default=False,
        ),
    ]
