# Generated by Django 4.0.2 on 2022-07-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_ticket_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='answer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
