# Generated by Django 4.0.2 on 2022-07-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_ticket_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NR', 'Not read yet'), ('A', 'Answered'), ('E', 'Evaluated'), ('D', 'Discarded')], default='NR', max_length=2),
        ),
    ]
